const colors = {
  light: {
    text: "#FFFFFF",
    tint: "#00D4FF",
    background: "#080810",
    foreground: "#FFFFFF",
    card: "#111120",
    cardForeground: "#FFFFFF",
    primary: "#00D4FF",
    primaryForeground: "#080810",
    secondary: "#1A1A2E",
    secondaryForeground: "#FFFFFF",
    muted: "#1A1A2E",
    mutedForeground: "#8A8A9A",
    accent: "#FF6B35",
    accentForeground: "#FFFFFF",
    destructive: "#FF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E1E30",
    input: "#1A1A2E",
    surface: "#16162A",
    calories: "#FF6B35",
    distance: "#00E676",
    steps: "#C56AFF",
    time: "#FFD60A",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#00D4FF",
    background: "#080810",
    foreground: "#FFFFFF",
    card: "#111120",
    cardForeground: "#FFFFFF",
    primary: "#00D4FF",
    primaryForeground: "#080810",
    secondary: "#1A1A2E",
    secondaryForeground: "#FFFFFF",
    muted: "#1A1A2E",
    mutedForeground: "#8A8A9A",
    accent: "#FF6B35",
    accentForeground: "#FFFFFF",
    destructive: "#FF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E1E30",
    input: "#1A1A2E",
    surface: "#16162A",
    calories: "#FF6B35",
    distance: "#00E676",
    steps: "#C56AFF",
    time: "#FFD60A",
  },
  radius: 16,
};

export default colors;
